#version: '3.8'
#services:
#  auth-service:
#    build: ./auth-service
#    ports:
#      - "3000:3000"
#
#  main-service:
#    build: ./todo
#    ports:
#      - "4000:4000"
#    environment:
#      - AUTH_SERVICE_URL=http://auth-service:3000
#    depends_on:
#      - auth-service


version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - '5672:5672' # Для соединений с RabbitMQ
      - '15672:15672' # Для доступа к панели управления RabbitMQ
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  auth-service:
    build: ./auth-service
    container_name: auth-service
    ports:
      - '3000:3000'
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672

  todo-service:
    build: ./todo-service
    container_name: todo
    ports:
      - '4000:4000'
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
